# Set this to "low" to reduce number of boot messages
verbosity: normal

# Try adjusting this if you have compatibility problems with other plguins.
# Default: "lowest". Can also use "low", "normal", "high", "highest".
priority: lowest

otherblocks:
##########
# This is a sample configuration file for OtherBlocks
# Configuration blocks are set out as followed:
#
# NAME_OF_ORIGINAL_BLOCK:
#     - tool: NAME_OF_TOOL (or ALL for all tools. Accepts lists like [toola, toolb])
#       world: WHICH_WORLD (optional. Accepts lists like [worlda, worldb])
#       drop: NAME_OF_NEW_DROP
#       color: COLOUR_OF_NEW_BLOCK (default WHITE, only applies to WOOL/DYE/INK_SACK drops)
#       quantity: AMOUNT_OF_NEW_DROP (optional, default 1)
#       damage: TOOL_DAMAGE (optional, default 1)
#       chance: DROP_PROBABILITY_PERCENTAGE (optional, default 100)
#
# For lists of appropriate values to use, see:
#  - Block and tools: http://cliqr.org/V
#  - Colors:          http://cliqr.org/Y
#
# If you want to add a different drop based on a
# different tool but for the same original block,
# simply repeat the indented block again, but make
# sure you start with "- tool", e.g.
#
# GRASS:
#     - tool: AIR
#       drop: GRAVEL
#
#     - tool: DIRT
#       drop: STONE
#
# A tool: ALL statement sets the drop for any
# tools not yet specified. Therefore, it should
# always be the last item in a list.
#
# Uncomment any of the blocks below to see some example
# behaviours
#
##########
# Drop Soulsand when you dig out
# gravel with a golden shovel
###
#        GRAVEL:
#            - tool: GOLD_SPADE
#              drop: SOUL_SAND
#              quantity: 1
#              damage: 4
##########
# Drop Glowstone Dust instead of
# Redstone when mined with a golden pick
# Note: redstone can also be glowing, so
# specify both
###
#        REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
#        GLOWING_REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
##########
# When you mine Gold with flint & steel,
# it comes pre-smelted!
###
#        GOLD_ORE:
#            - tool: FLINT_AND_STEEL
#              drop: GOLD_INGOT
#              quantity: 1
##########
# The leaves are now diamonds!
###
#        LEAVES:
#            - tool: AIR
#              drop: DIAMOND
#              quantity: 1
#              chance: 33
##########
