# Set this to "low" to reduce number of boot messages
verbosity: normal

# Try adjusting this if you have compatibility problems with other plguins.
# Default: "lowest". Can also use "low", "normal", "high", "highest".
priority: lowest

# experimental water damage (DANGEROUS - disabled above "enableblockto")
# supposed to allow you to change the drop if a torch is destroyed by water (DAMAGE_WATER, doesn't work yet)
# this setting CAN crash your server if set to true and configured incorrectly
enableblockto: false

otherblocks:
##########
# This is a sample configuration file for OtherBlocks
# Configuration blocks are set out as followed:
#
# NAME_OF_ORIGINAL_BLOCK:
#     - tool: NAME_OF_TOOL (or ALL for all tools. Accepts lists like [toola, toolb])
#       world: WHICH_WORLD (optional. Accepts lists like [worlda, worldb])
#       drop: NAME_OF_NEW_DROP
#       color: COLOUR_OF_NEW_BLOCK (default WHITE, only applies to WOOL/DYE/INK_SACK drops)
#       quantity: AMOUNT_OF_NEW_DROP (optional, default 1)
#       damage: TOOL_DAMAGE (optional, default 1)
#       chance: DROP_PROBABILITY_PERCENTAGE (optional, default 100)
#		time: DAY or NIGHT (optional, drop only occurs during day or night)
#
# For lists of appropriate values to use, see:
#  - Block and tools: http://cliqr.org/V
#  - Colors:          http://cliqr.org/Y
#
# If you want to add a different drop based on a
# different tool but for the same original block,
# simply repeat the indented block again, but make
# sure you start with "- tool", e.g.
#
# GRASS:
#     - tool: AIR
#       drop: GRAVEL
#
#     - tool: DIRT
#       drop: STONE
#
# A tool: ALL statement sets the drop for any
# tools not yet specified. Therefore, it should
# always be the last item in a list.
#
# Uncomment any of the blocks below to see some example
# behaviours
#
##########
# Drop Soulsand when you dig out
# gravel with a golden shovel
###
#        GRAVEL:
#            - tool: GOLD_SPADE
#              drop: SOUL_SAND
#              quantity: 1
#              damage: 4
##########
# Drop Glowstone Dust instead of
# Redstone when mined with a golden pick
# Note: redstone can also be glowing, so
# specify both
###
#        REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
#        GLOWING_REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
##########
# When you mine Gold with flint & steel,
# it comes pre-smelted!
###
#        GOLD_ORE:
#            - tool: FLINT_AND_STEEL
#              drop: GOLD_INGOT
#              quantity: 1
##########
# The leaves are now diamonds! (when punched)
###
#        LEAVES:
#            - tool: AIR
#              drop: DIAMOND
#              quantity: 1
#              chance: 33
##########
# Generic leaves drop apples (on decay and harvest, higher chance for harvesting manually)
###
#        SPECIAL_LEAFDECAY@GENERIC:
#            - tool: ALL
#              drop: APPLE
#              quantity: 1
#              chance: 5
#        LEAVES@GENERIC:
#            - tool: ALL
#              drop: APPLE
#              quantity: 1
#              chance: 15
##########
# Grass has a 5% chance of dropping seeds during day, 5% chance of dropping brown mushroom at night
###
#        GRASS:
#            - tool: ALL
#              drop: SEEDS
#              quantity: 1-3
#              chance: 5
#              time: DAY
#            - tool: ALL
#              drop: BROWN_MUSHROOM
#              quantity: 1
#              chance: 5
#              time: NIGHT
##########
# Saddled pigs drop their saddles
###
#        PIG@SADDLED:
#            - tool: ALL
#              drop: SADDLE
#              quantity: 1
##########
# Glass drops glass
###
#        GLASS:
#            - tool: ALL
#              drop: GLASS
#              quantity: 1
##########
# Bookshelves drop bookshelves (with axe)
###
#        BOOKSHELF:
#            - tool: ANY_AXE
#              drop: BOOKSHELF
#              quantity: 1
##########
# Boats drop boats
###
#        BOAT:
#            - tool: ALL
#              drop: BOAT
#              quantity: 1
##########

