# Set this to "low" to reduce number of boot messages
verbosity: normal

# Try adjusting this if you have compatibility problems with other plguins.
# Default: "lowest". Can also use "low", "normal", "high", "highest".
priority: lowest

# experimental water damage (DANGEROUS - disabled above "enableblockto")
# supposed to allow you to change the drop if a torch is destroyed by water (DAMAGE_WATER, doesn't work yet)
# this setting CAN crash your server if set to true and configured incorrectly
enableblockto: false

# set to true to use the permissions sytem (ensure users have the "otherblocks.active" permission)
usepermissions: false

otherblocks:
##########
# This is a sample configuration file for OtherBlocks
# Configuration blocks are set out as followed:
#
# NAME_OF_ORIGINAL_BLOCK:
#     - tool: NAME_OF_TOOL (or ALL for all tools. Accepts lists like [toola, toolb])
#       world: WHICH_WORLD (optional. Accepts lists like [worlda, worldb])
#       drop: NAME_OF_NEW_DROP (can be any block/item or MONEY [see money section])
#
### Optional parameters ###
#
#       color: COLOUR_OF_NEW_BLOCK (default WHITE, only applies to WOOL/DYE/INK_SACK drops)
#       quantity: AMOUNT_OF_NEW_DROP (optional, default 1)
#       damage: TOOL_DAMAGE (optional, default 1)
#       chance: DROP_PROBABILITY_PERCENTAGE (optional, default 100)
#       permissiongroup: list of groups this applies to (eg. [Citizen,Moderator]) not case sensitive
#       permissiongroupexcept: apply this drop to all groups _except_ this list
#       message: Message to be shown to the player on a drop (can be a list - one gets selected at random)
#		time: DAY or NIGHT (optional, drop only occurs during day or night)
#       weather: RAIN, THUNDER, CLEAR (accepts lists eg. [RAIN, THUNDER])
#       event: LIGHTNING, TREE, EXPLOSION (accompany the drop with an event)
#                     also TREE@BIG_TREE, TREE@BIRCH, TREE@REDWOOD, TREE@TALL_REDWOOD
#          !!!BEWARE!!! - there is no check to see if chests are destroyed with trees
#
# For lists of appropriate values to use, see:
#  - Block and tools: http://cliqr.org/V
#  - Colors:          http://cliqr.org/Y
#
# If you want to add a different drop based on a
# different tool but for the same original block,
# simply repeat the indented block again, but make
# sure you start with "- tool", e.g.
#
#### Money
#
#   For money drops use MONEY in the drop parameter and the amount in the "quantity" parameter.
#
#   Amounts can be decimal eg. "quantity: 0.5-1.67".
#   For negatives use a ~ character as the separator eg. "quantity: -5.5~-2.5"
#
######
# Examples
######
#
# GRASS:
#     - tool: AIR
#       drop: GRAVEL
#
#     - tool: DIRT
#       drop: STONE
#
# A tool: ALL statement sets the drop for any
# tools not yet specified. Therefore, it should
# always be the last item in a list.
#
# Uncomment any of the blocks below to see some example
# behaviours
#
##########
# Drop Soulsand when you dig out
# gravel with a golden shovel
###
#        GRAVEL:
#            - tool: GOLD_SPADE
#              drop: SOUL_SAND
#              quantity: 1
#              damage: 4
##########
# Drop Glowstone Dust instead of
# Redstone when mined with a golden pick
# Note: redstone can also be glowing, so
# specify both
###
#        REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
#        GLOWING_REDSTONE_ORE:
#            - tool: GOLD_PICKAXE
#              drop: GLOWSTONE_DUST
#              quantity: 4
##########
# When you mine Gold with flint & steel,
# it comes pre-smelted!
###
#        GOLD_ORE:
#            - tool: FLINT_AND_STEEL
#              drop: GOLD_INGOT
#              quantity: 1
##########
# The leaves are now diamonds! (when punched)
###
#        LEAVES:
#            - tool: AIR
#              drop: DIAMOND
#              quantity: 1
#              chance: 33
##########
# Generic leaves drop apples (on decay and harvest, higher chance for harvesting manually)
###
#        SPECIAL_LEAFDECAY@GENERIC:
#            - tool: ALL
#              drop: APPLE
#              quantity: 1
#              chance: 5
#        LEAVES@GENERIC:
#            - tool: ALL
#              drop: APPLE
#              quantity: 1
#              chance: 15
##########
# Grass has a 5% chance of dropping seeds during day, 5% chance of dropping brown mushroom at night
###
#        GRASS:
#            - tool: ALL
#              drop: SEEDS
#              quantity: 1-3
#              chance: 5
#              time: DAY
#            - tool: ALL
#              drop: BROWN_MUSHROOM
#              quantity: 1
#              chance: 5
#              time: NIGHT
##########
# Saddled pigs drop their saddles
###
#        PIG@SADDLED:
#            - tool: ALL
#              drop: SADDLE
#              quantity: 1
##########
# Glass drops glass
###
#        GLASS:
#            - tool: ALL
#              drop: GLASS
#              quantity: 1
##########
# Bookshelves drop bookshelves (with axe)
###
#        BOOKSHELF:
#            - tool: ANY_AXE
#              drop: BOOKSHELF
#              quantity: 1
##########
# Boats drop boats
###
#        BOAT:
#            - tool: ALL
#              drop: BOAT
#              quantity: 1
##########
# Economy examples
#
## Killing skeletons gives between 10.25 and 50.45 currency
#        CREATURE_SKELETON:
#            - tool: ANY_SWORD
#              drop: MONEY
#              quantity: 10.25-50.45
#
## Killing sheep subtracts between -10 and -2 currency 
#        CREATURE_SHEEP:
#            - tool: ANY_SWORD
#              drop: MONEY
#              quantity: -10~-2
#              message: You killed a poor sheep :(  Lose %q currency.
##########
## Were you wishing you could have "powered creepers at night in a thunderstorm" have a 66% chance to 
## drop diamonds (accompanied by with a bolt of lightning) only when hit with a golden sword? Now you can :D
#        CREATURE_CREEPER@POWERED:
#            - tool: GOLD_SWORD
#              drop: DIAMOND
#              quantity: 10
#              chance: 66
#              time: NIGHT
#              weather: THUNDER
#              event: LIGHTNING
#
## Unfortunately the lighting also zaps the diamonds :/  (will fix if I can) 
##########
#
#       GRASS:
## find money in the grass only during a clear day (can't see as well as
## at night or raining)
#            - tool: ALL
#              drop: MONEY
#              quantity: 2
#              chance: 5
#              message: ["Someone dropped their change in the grass.","It's your lucky day - found some change."]
#              time: DAY
#              weather: CLEAR
## chance of a mushroom at night whilst raining
#            - tool: ALL
#              drop: BROWN_MUSHROOM
#              quantity: 1
#              chance: 10
#              time: NIGHT
#              weather: RAIN
## chance of a diamond at night during a thunderstorm accompanied by
## a thunderstrike (which also destroys the diamond - oh well :D)
#            - tool: ALL
#              drop: DIAMOND
#              chance: 5
#              time: NIGHT
#              weather: THUNDER
#              event: LIGHTNING
