# Set this to "low" to reduce number of boot messages or to high, highest, extreme for more debugging info
verbosity: normal

# Try adjusting this if you have compatibility problems with other plugins.
# High means that this runs after plugins on low & normal priority (this is usually a good thing)
# Default: "high". Can also use "low", "normal", "high", "highest".
priority: high

##########
# Include files
##
# The plugin will scan through and load these files (if set to 'yes') after loading the main config below.
# Extension ".yml" is added automatically before searching for the file
#
# Note: drops from included files will are inclusive and will all be added to the drop list.
# Note when updating OtherBlocks: these files may be updated from time to time - rename them if you don't want to overwrite them.
#
include-files: 
## OtherBlocks example files
    ob-fix_undroppables: no      # fix glass, bookshelf, boat and stairs drops
    ob-goldtools-basic: no       # allow gold-pickaxe chance to get ice & glowstone, gold-hoe chance to get grass
    ob-goldtools-smelt: no       # gold-pickaxe smelts ores to ingots, sand to glass, etc
    ob-ore_extraction: no        # allow ore to seem to be "extracted" - leaving behind stone
    ob-leaf_overhaul: no         # overhaul leaf drops (apples, cocoa beans, leaves, sticks & a very small chance of golden apple)
    ob-playerdeath_zombie: no    # players drop zombies on death (that's it - see undead_chaos for more fun :D)
    ob-undead_chaos: no          # the undead shall rise again! Includes players dropping zombies/skeletons
#    ob-random_examples: no      # For crazy testing only :) Read through examples before activating.

## Other users overhauls
    overhaul-catballs: no        # great example/playable config from Catballs (disable "ob" configs before using this one, otherwise you might have too many drops)
    overhaul-zarius: no          # Zar's messy config (I run this with no other includes, at the moment)
    
## Add your files here (alternatively just add your custom drops to the bottom of this file)
    #my_custom_file1: yes

##########	
otherblocks:

#
# Your changes here, or create a new .yml file and include it above in the "include-files" section
# Explore the included config files for many more examples
#
# If make a interesting or crazy config let me know on the forum and I might include it in the next release
#
#

# Example:
#    GLASS:
#        - drop: GLASS
#          
#        - drop: MONEY
#          quantity: 3-15
#          message: You recycled the glass for %q dollars.


