# Set this to "low" to reduce number of boot messages or to high, highest, extreme for more debugging info
verbosity: normal

# Number of decimal places to round money drops off to (for the drop and message)
money-precision: 2

# Set this to false if you don't want blocks to drop their custom configs upon explosions (eg. tnt/creepers)
customdropsforexplosions: true

# Set this to false if you want items to drop as a single stack (true=individual item drops, like lapis drops from lapis ore)
default_dropspread: true

# Set this to true if you want XP drops to be cancelled when configuring mob drops (unless there is a default drop)
# - this means you need to set an XP drop yourself if you want any XP to drop
disable_xp_on_non_default: false

# Ignore level: allow enchantments to ignore start and/or max level (eg. dig_speed#50)
# note: enchantments_ignore_level requires enchantments_use_unsafe to be true
enchantments_ignore_level: false

# Use unsafe: allow any enchantment on any item/tool (eg. DIRT@!DAMAGE_ALL#3)
enchantments_use_unsafe: false


# Allow any replacement block (by default non-safe replacements, eg. items, are blocked as they will crash the client)
allow_any_replacementblock: false

# Override explosion cap (normally capped at max power 100f to avoid crashing server)
override_explosion_cap: false

## Override Defaults ##

money_overrides_default: false  # set true to have money drops override default drops
xp_overrides_default: false     # set true to have xp drops override default drops
loot_overrides_default: true    # set true to have loot (anything other than money or xp, includes mobs) drops override default drops


# Disable anonymous logging - set this to true if you get errors in older Tekkit or Bukkit versions on startup
disable_metrics: false


# Restore standard config/include files if they are deleted
restore_deleted_config_files: true

# OtherDrops will stop spawning new mobs if the number of living entities in the current world is higher
# this only affects the mobspawn trigger
custom_spawn_limit: 150