# Set this to "low" to reduce number of boot messages or to high, highest, extreme for more debugging info
verbosity: normal

# Try adjusting this if you have compatibility problems with other plugins.
# Default: "high". Can also use "low", "normal", "high", "highest".
priority: high

# Set this to false if you are having problems with permissions
usepermissions: true
