otherblocks:
##########
# This is a sample configuration file for OtherBlocks
# Configuration blocks are set out as followed:
#
# NAME_OF_ORIGINAL_BLOCK:
#     - tool: NAME_OF_TOOL
#     - drop: NAME_OF_NEW_DROP
#       quantity: AMOUNT_OF_NEW_DROP
#
# You can repeat this as many times as you like within
# the "otherblocks" key. You can also specify the same
# original block multiple times if you want it to drop
# different things based on what tool you are using
#
# For the list of names you can use for the blocks
# and tools, please see http://cliqr.org/V
#
# Uncomment any of the blocks below to see some example
# behaviours
#
#
##########
# Drop Soulsand when you dig out
# gravel with a golden shovel
###
#    GRAVEL:
#        tool: GOLD_SPADE
#        drop: SOUL_SAND
#        quantity: 1
##########
# Drop Glowstone Dust instead of
# Redstone when mined with a golden pick
# Note: redstone can also be glowing, so
# specify both
###
#    REDSTONE_ORE:
#        tool: GOLD_PICKAXE
#        drop: GLOWSTONE_DUST
#        quantity: 4
#    GLOWING_REDSTONE_ORE:
#        tool: GOLD_PICKAXE
#        drop: GLOWSTONE_DIST
#        quantity: 4
##########
# When you mine Gold with a diamond pickaxe,
# it comes pre-smelted!
###
#    GOLD_ORE:
#        tool: DIAMOND_PICKAXE
#        drop: GOLD_INGOT
#        quantity: 1
##########
# The leaves are now diamonds!
###
#    LEAVES:
#        tool: AIR
#        drop: DIAMOND
#        quantity: 1
##########