name: OtherBlocks
main: com.gmail.zariust.bukkit.otherblocks.OtherBlocks
version: 2.0
authors:
  - cyklo
  - Celtic Minstrel
  - Zarius
commands:
    ob:
        description: Administrate the OtherBlocks plugin
        aliases: [obreload, obr, obshow, obs, obprofile, obp]
        usage: |
            /ob show <block>
            /ob profile <stuff>
softdepend:
  - BigBrother
  - WorldGuard
  - LogBlock