name: OtherDrops
main: com.gmail.zariust.otherdrops.OtherDrops
version: 2.5.1
authors:
  - cyklo
  - Celtic Minstrel
  - Zarius
commands:
    od:
        description: Administrate the OtherDrops plugin
        aliases: [odreload, odr, odshow, ods, odprofile, odp, ode, odd]
        usage: |
            /od show <block>
            /od profile on
            /od profile off
            /od profile <event> [avg]
            /od reload - reload config
softdepend:
  - BigBrother
  - WorldGuard
  - LogBlock
  - HawkEye
permissions:
    otherdrops.admin.id:
        default: op
        description: Gives permission to ID items (show name@data).
    otherdrops.admin.reloadconfig:
        default: op
        description: Gives permission to reload the config files for OtherDrops.
    otherdrops.admin.show:
        default: op
        description: Gives permission to show the registered drops.
    otherdrops.admin.profiling:
        default: op
        description: Gives permission to use profiling commands.
        