name: OtherBlocks
main: com.gmail.zariust.bukkit.otherblocks.OtherBlocks
version: 1.5beta1
authors:
  - cyklo
  - Celtic Minstrel
  - Zarius
commands:
    otherblocksreload:
        description: Reload otherblocks config
        usage: /otherblocksreload
    obr:
        description: Reload otherblocks config
        usage: /obr