name: OtherBlocks
main: com.sargant.bukkit.otherblocks.OtherBlocks
version: 0.8.1z
authors:
  - cyklo
  - Celtic Minstrel
  - Xarqn
commands:
    otherblocksreload:
        description: Reload otherblocks config
        usage: /otherblocksreload
    obr:
        description: Reload otherblocks config
        usage: /obr
        