name: OtherBlocks
main: com.gmail.zariust.bukkit.otherblocks.OtherBlocks
version: 1.7
authors:
  - cyklo
  - Celtic Minstrel
  - Zarius
commands:
    otherblocksreload:
        description: Reload otherblocks config
        usage: /otherblocksreload
    obr:
        description: Reload otherblocks config
        usage: /obr
    ob:
        description: <show> shows configured drops for the block
        usage: /ob show <block>