name: OtherBlocks
main: com.sargant.bukkit.otherblocks.OtherBlocks
version: 1.0-beta2
authors:
  - cyklo
  - Celtic Minstrel
  - Xarqn
commands:
    otherblocksreload:
        description: Reload otherblocks config
        usage: /otherblocksreload
    obr:
        description: Reload otherblocks config
        usage: /obr
